--CREATE DATABASE CASHIERQUEUE
--USE CASHIERQUEUE

CREATE TABLE ROL (
idRol INT IDENTITY PRIMARY KEY NOT NULL,
nombre VARCHAR(20) NOT NULL
)

INSERT INTO ROL (nombre) VALUES ('ADMINISTRADOR')
INSERT INTO ROL (nombre) VALUES ('USUARIO')


CREATE TABLE CAJAS (
    idCaja INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    isLogged BIT NOT NULL,
);


CREATE TABLE USUARIO (
    idUsuario INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    nombre VARCHAR(20) NOT NULL,
    apellido VARCHAR(20) NOT NULL,
    usuario VARCHAR(20) UNIQUE NOT NULL,
    rol INT NOT NULL,
	idCaja INT NOT NULL,
	activo BIT NOT NULL,
    FOREIGN KEY (rol) REFERENCES ROL(idRol),
    FOREIGN KEY (idCaja) REFERENCES CAJAS(idCaja)
);

